# Generated by Django 5.0 on 2024-02-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagespace',
            name='name',
            field=models.CharField(default='first', max_length=200),
        ),
    ]
