# Generated by Django 5.0 on 2024-02-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_storagespace_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=200)),
                ('name', models.CharField(choices=[('wheat', 'Wheat'), ('rice', 'Rice'), ('corn', 'Corn')], max_length=200)),
                ('type', models.CharField(choices=[('kharif', 'Kharif '), ('rabi', 'Rabi '), ('zaid ', 'Zaid ')], max_length=200)),
                ('time_of_harvest', models.CharField(max_length=200)),
                ('best_time_to_grow', models.CharField(max_length=200)),
                ('medicines_pesticides', models.CharField(max_length=200)),
                ('soil', models.CharField(max_length=200)),
            ],
        ),
    ]
