# Generated by Django 5.0 on 2024-02-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagespace',
            name='availability_duration',
            field=models.CharField(default='January', max_length=12),
        ),
        migrations.AddField(
            model_name='storagespace',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
