# Generated by Django 5.0 on 2024-02-29 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_storagespace_availability_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='crop_image',
            field=models.ImageField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
    ]
