# Generated by Django 5.0 on 2024-03-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_crop_crop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagespace',
            name='is_shared',
        ),
        migrations.AddField(
            model_name='storagespace',
            name='storage_type',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold')], default=None, max_length=20),
        ),
    ]
