# Generated by Django 5.0 on 2024-03-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_storagespace_is_shared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='storage_type',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold')], default='Hot', max_length=20),
        ),
    ]
