# Generated by Django 5.0 on 2024-03-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_storagespace_storage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='storage_type',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold')], default='hot', max_length=20, null=True),
        ),
    ]
