# Generated by Django 5.0 on 2024-03-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_storagespace_storage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagespace',
            name='storage_type',
        ),
    ]
