# Generated by Django 5.0 on 2024-03-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_storagespace_storage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagespace',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('cold', 'Cold')], max_length=20, null=True),
        ),
    ]
