# Generated by Django 5.0 on 2024-03-02 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_storagespace_storage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagespace',
            name='availability_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
