# Generated by Django 5.0 on 2024-03-03 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_storagespace_availability_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='best_time_to_grow',
        ),
        migrations.AddField(
            model_name='storagespace',
            name='available_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='storagespace',
            name='availability_duration',
            field=models.IntegerField(default=1, max_length=3),
        ),
    ]
