# Generated by Django 5.0 on 2024-03-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_crop_best_time_to_grow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='time_of_harvest',
            new_name='month_of_harvest',
        ),
    ]
