# Generated by Django 5.0 on 2024-03-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_time_of_harvest_crop_month_of_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagespace',
            name='price',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='storagespace',
            name='availability_duration',
            field=models.IntegerField(blank=True, default='1'),
        ),
    ]
