# Generated by Django 5.0 on 2024-03-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_storagespace_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagespace',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
