# Generated by Django 5.0 on 2024-03-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_storagespace_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='available',
            field=models.CharField(default=False, max_length=6),
        ),
    ]
