# Generated by Django 5.0 on 2024-03-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_storagespace_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='available',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=False, max_length=6),
        ),
    ]
