# Generated by Django 5.0 on 2024-03-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_storagespace_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagespace',
            name='booked_quantity',
            field=models.FloatField(default=0),
        ),
    ]
