# Generated by Django 5.0 on 2024-03-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_storagespace_booked_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='available',
            field=models.CharField(max_length=6, default=False),
        )
    ]
