# Generated by Django 5.0 on 2024-03-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_storagespace_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagespace',
            name='booked_quantity',
        ),
    ]
