# Generated by Django 5.0 on 2024-03-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_crop_soil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='crop',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
