# Generated by Django 5.0 on 2024-03-09 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_crop_name_alter_crop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='available_from',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
