# Generated by Django 5.0 on 2024-03-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_storagespace_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='available_from',
            field=models.CharField(blank=True, null=True),
        ),
    ]
