# Generated by Django 5.0 on 2024-03-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_storagespace_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='storage_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
