# Generated by Django 5.0 on 2024-03-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_storagespace_storage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='medicines_pesticides',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
