# Generated by Django 5.0 on 2024-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_crop_medicines_pesticides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_image',
            field=models.CharField(max_length=1000),
        ),
    ]
