# Generated by Django 5.0 on 2024-03-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_storagespace_storage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagespace',
            old_name='crop_image',
            new_name='storage_image',
        ),
    ]
