# Generated by Django 5.0 on 2024-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_crop_image_storagespace_storage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='storage_image',
            field=models.ImageField(default='default_image_path', max_length=1000, upload_to=''),
        ),
    ]
